import boto3
import json
import uuid
import os
from datetime import datetime

healthlake = boto3.client("healthlake")


def map_entities_to_fhir(entities):
    """Maps the raw AI-extracted entities dictionary into a valid FHIR R4 Patient resource."""
    # Extract Patient Name safely
    patient_name = entities.get("PatientName", "Unknown Patient")

    # Handle name splitting (First/Last)
    name_parts = patient_name.split()
    family = name_parts[-1] if len(name_parts) > 1 else patient_name
    given = name_parts[:-1] if len(name_parts) > 1 else [patient_name]

    # Create the FHIR Resource
    return {
        "resourceType": "Patient",
        "id": str(uuid.uuid4()),
        "meta": {
            "profile": ["http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"]
        },
        "text": {
            "status": "generated",
            "div": f"\n\nGenerated by AI Pipeline. Raw Data: {json.dumps(entities)}\n\n",
        },
        "name": [
            {
                "use": "official",
                "family": family,
                "given": given,
                "text": patient_name,
            }
        ],
        # Store other raw entities (Vitals, Meds) in extension or containment if needed
        # For this workshop, storing the raw dump in 'text.div' (above) is sufficient for visibility.
    }


def _is_unknown(v):
    if v is None:
        return True
    if isinstance(v, str) and v.strip().upper() in {"", "<UNKNOWN>", "UNKNOWN", "N/A", "NA", "NONE"}:
        return True
    return False


def _entities_have_signal(entities: dict) -> bool:
    """
    Avoid ingesting chunks that are marked VALID but contain no useful extracted info.
    """
    if not isinstance(entities, dict) or not entities:
        return False

    # If any field is not unknown, treat as signal
    for k in ("PatientName", "Vitals", "Medications"):
        if k in entities and not _is_unknown(entities.get(k)):
            return True
    return False


def lambda_handler(event, context):
    # Event is LIST of results from Map State
    results = event if isinstance(event, list) else []

    # --- FIX START: Smart Aggregation Logic ---
    valid_results = [r for r in results if r.get("classification") == "VALID"]
    invalid_results = [r for r in results if r.get("classification") == "INVALID"]

    # If we found NO valid chunks at all, then it's a truly invalid file.
    if not valid_results:
        reason = (
            invalid_results[0].get("reason", "No valid medical content found in any chunk.")
            if invalid_results
            else "No valid medical content found in any chunk."
        )
        print(f"SECURITY BLOCK: File rejected. Reason: {reason}")
        return {"status": "REJECTED", "reason": reason}

    print(
        f"Processing {len(valid_results)} valid chunks. Ignored {len(invalid_results)} invalid/boilerplate chunks."
    )

    # Use metadata from the first VALID chunk (safer than using possibly-invalid chunk[0])
    metadata = valid_results[0].get("metadata", {}) if valid_results else {}
    # --- FIX END ---

    source_agent = metadata.get("sender", "Web Upload")
    print(f"Ingesting clean data verified from source: {source_agent}")

    # Construct FHIR Entries (only from VALID chunks with usable entities)
    entries = []

    for res in valid_results:
        entities = res.get("entities", {})

        # Skip VALID chunks that extracted nothing useful (prevents noisy duplicates)
        if not _entities_have_signal(entities):
            continue

        # Map entities to FHIR if needed
        if "fhir_resource" not in res:
            print("Detected raw entities. Mapping to FHIR Patient resource...")
            res["fhir_resource"] = map_entities_to_fhir(entities)

        if "fhir_resource" in res:
            entries.append(
                {
                    "resource": res["fhir_resource"],
                    "request": {
                        "method": "POST",
                        "url": res["fhir_resource"]["resourceType"],
                    },
                }
            )

    if not entries:
        print("No FHIR resources generated (valid chunks contained no mapped entities).")
        return {"status": "SKIPPED", "reason": "No entities extracted"}

    # ACTUAL WRITE TO HEALTHLAKE
    try:
        success_count = 0
        for entry in entries:
            # Using create_resource loop for workshop reliability
            healthlake.create_resource(
                DatastoreId=os.environ["HEALTHLAKE_ID"],
                Resource=json.dumps(entry["resource"]),
            )
            success_count += 1

        print(f"Successfully ingested {success_count} resources into HealthLake.")

    except Exception as e:
        print(f"Error writing to HealthLake: {str(e)}")
        raise e

    return {"status": "SUCCESS", "items_processed": success_count}
